import type { Genre } from '../src/app/core/models/book';

/** Hand-curated editorial layer. Open Library supplies cover/isbn/year at build
 *  time (scripts/fetch-seed.ts); everything here is the part a shop owner writes. */
export interface CuratedBook {
  title: string;
  author: string;
  genre: Genre;
  price: number;
  rating: number;
  likeCount: number;
  pageCount: number;
  tags: string[];
  description: { de: string; en: string };
  /** Overrides for the Open Library lookup when the display title differs. */
  query?: { title: string; author?: string };
}

export const curatedBooks: CuratedBook[] = [
  // ── Fantasy ────────────────────────────────────────────────
  {
    title: 'Die unendliche Geschichte',
    author: 'Michael Ende',
    genre: 'Fantasy',
    price: 16.99,
    rating: 4.8,
    likeCount: 4210,
    pageCount: 480,
    tags: ['Klassiker', 'Abenteuer', 'Phantásien', 'Kindheit'],
    description: {
      de: 'Bastian flüchtet sich in ein Buch – und wird selbst Teil der Rettung des untergehenden Reiches Phantásien.',
      en: 'Bastian escapes into a book and becomes the only hope for the vanishing realm of Fantastica.',
    },
  },
  {
    title: 'Momo',
    author: 'Michael Ende',
    genre: 'Fantasy',
    price: 14.0,
    rating: 4.7,
    likeCount: 3105,
    pageCount: 304,
    tags: ['Klassiker', 'Zeit', 'Freundschaft'],
    description: {
      de: 'Ein Mädchen mit der Gabe des Zuhörens stellt sich den grauen Herren, die den Menschen ihre Zeit stehlen.',
      en: 'A girl who truly listens takes on the grey men stealing humanity’s time.',
    },
  },
  {
    title: 'Tintenherz',
    author: 'Cornelia Funke',
    genre: 'Fantasy',
    price: 12.99,
    rating: 4.5,
    likeCount: 2540,
    pageCount: 576,
    tags: ['Bücher', 'Abenteuer', 'Jugend'],
    description: {
      de: 'Meggies Vater kann Figuren aus Büchern herauslesen – bis ein Schurke der Wirklichkeit entkommt.',
      en: 'Meggie’s father can read characters out of books — until a villain escapes into the real world.',
    },
  },
  {
    title: 'Der Herr der Ringe',
    author: 'J. R. R. Tolkien',
    genre: 'Fantasy',
    price: 28.0,
    rating: 4.9,
    likeCount: 8800,
    pageCount: 1280,
    tags: ['Epos', 'Mittelerde', 'Klassiker'],
    description: {
      de: 'Ein Hobbit trägt den Einen Ring quer durch Mittelerde, um die Macht des Dunklen Herrschers zu brechen.',
      en: 'A hobbit carries the One Ring across Middle-earth to unmake the Dark Lord’s power.',
    },
    query: { title: 'The Lord of the Rings', author: 'Tolkien' },
  },
  {
    title: 'Harry Potter und der Stein der Weisen',
    author: 'J. K. Rowling',
    genre: 'Fantasy',
    price: 9.99,
    rating: 4.8,
    likeCount: 9600,
    pageCount: 336,
    tags: ['Zauberei', 'Internat', 'Jugend'],
    description: {
      de: 'Ein Waisenjunge erfährt an seinem elften Geburtstag, dass er ein Zauberer ist – und ein Schicksal hat.',
      en: 'On his eleventh birthday an orphan learns he is a wizard — and that destiny awaits at Hogwarts.',
    },
    query: { title: "Harry Potter and the Philosopher's Stone", author: 'Rowling' },
  },
  {
    title: 'Der Name des Windes',
    author: 'Patrick Rothfuss',
    genre: 'Fantasy',
    price: 15.0,
    rating: 4.6,
    likeCount: 3320,
    pageCount: 864,
    tags: ['Magie', 'Musik', 'Erzählung'],
    description: {
      de: 'Der berüchtigte Kvothe erzählt selbst, wie aus einem Gauklerkind eine Legende wurde.',
      en: 'The infamous Kvothe recounts how a travelling player’s child became a living legend.',
    },
    query: { title: 'The Name of the Wind', author: 'Rothfuss' },
  },
  // ── Romantik ───────────────────────────────────────────────
  {
    title: 'Stolz und Vorurteil',
    author: 'Jane Austen',
    genre: 'Romantik',
    price: 8.0,
    rating: 4.7,
    likeCount: 6100,
    pageCount: 480,
    tags: ['Klassiker', 'England', 'Gesellschaft'],
    description: {
      de: 'Elizabeth Bennet und der hochmütige Mr. Darcy ringen zwischen Vorurteil und wachsender Zuneigung.',
      en: 'Elizabeth Bennet and the proud Mr Darcy spar their way from prejudice to love.',
    },
    query: { title: 'Pride and Prejudice', author: 'Austen' },
  },
  {
    title: 'Wie ein einziger Tag',
    author: 'Nicholas Sparks',
    genre: 'Romantik',
    price: 11.0,
    rating: 4.3,
    likeCount: 2870,
    pageCount: 256,
    tags: ['Liebe', 'Erinnerung', 'Drama'],
    description: {
      de: 'Eine große Liebe trotzt der Zeit – und einer Krankheit, die alle Erinnerung auszulöschen droht.',
      en: 'A lifelong love endures against time and an illness threatening to erase every memory.',
    },
    query: { title: 'The Notebook', author: 'Sparks' },
  },
  {
    title: 'Vom Winde verweht',
    author: 'Margaret Mitchell',
    genre: 'Romantik',
    price: 13.5,
    rating: 4.4,
    likeCount: 3450,
    pageCount: 1024,
    tags: ['Klassiker', 'Epos', 'Südstaaten'],
    description: {
      de: 'Scarlett O’Hara kämpft im zerfallenden Süden um Land, Liebe und das eigene Überleben.',
      en: 'Scarlett O’Hara fights for land, love and survival in the collapsing American South.',
    },
    query: { title: 'Gone with the Wind', author: 'Mitchell' },
  },
  {
    title: 'Der Vorleser',
    author: 'Bernhard Schlink',
    genre: 'Romantik',
    price: 10.0,
    rating: 4.2,
    likeCount: 1980,
    pageCount: 208,
    tags: ['Nachkriegszeit', 'Schuld', 'Deutschland'],
    description: {
      de: 'Eine Affäre zwischen einem Jungen und einer älteren Frau führt Jahre später in einen Kriegsverbrecherprozess.',
      en: 'A teenager’s affair with an older woman resurfaces years later in a war-crimes trial.',
    },
    query: { title: 'Der Vorleser', author: 'Schlink' },
  },
  {
    title: 'Schokolade zum Frühstück',
    author: 'Marian Keyes',
    genre: 'Romantik',
    price: 11.0,
    rating: 4.1,
    likeCount: 1420,
    pageCount: 624,
    tags: ['Humor', 'Familie', 'Neuanfang'],
    description: {
      de: 'Nach dem Ende ihrer Ehe sucht Rachel zwischen Chaos und Komik einen Weg zurück ins Leben.',
      en: 'After her marriage falls apart, Rachel finds her way back to life through chaos and comedy.',
    },
    query: { title: 'Rachel’s Holiday', author: 'Marian Keyes' },
  },
  // ── Science-Fiction ────────────────────────────────────────
  {
    title: 'Per Anhalter durch die Galaxis',
    author: 'Douglas Adams',
    genre: 'Science-Fiction',
    price: 12.0,
    rating: 4.7,
    likeCount: 5400,
    pageCount: 256,
    tags: ['Humor', 'Weltraum', 'Kult'],
    description: {
      de: 'Kurz vor der Sprengung der Erde wird Arthur Dent ins absurdeste Abenteuer der Galaxis gerissen.',
      en: 'Moments before Earth is demolished, Arthur Dent is swept into the galaxy’s most absurd adventure.',
    },
    query: { title: "The Hitchhiker's Guide to the Galaxy", author: 'Adams' },
  },
  {
    title: 'Der Marsianer',
    author: 'Andy Weir',
    genre: 'Science-Fiction',
    price: 13.0,
    rating: 4.6,
    likeCount: 4720,
    pageCount: 416,
    tags: ['Mars', 'Survival', 'Wissenschaft'],
    description: {
      de: 'Allein auf dem Mars zurückgelassen, kämpft ein Astronaut mit Ingenieurskunst und Humor ums Überleben.',
      en: 'Stranded alone on Mars, an astronaut science-and-jokes his way toward survival.',
    },
    query: { title: 'The Martian', author: 'Weir' },
  },
  {
    title: 'Dune – Der Wüstenplanet',
    author: 'Frank Herbert',
    genre: 'Science-Fiction',
    price: 16.0,
    rating: 4.7,
    likeCount: 6300,
    pageCount: 816,
    tags: ['Epos', 'Politik', 'Wüste'],
    description: {
      de: 'Auf dem Wüstenplaneten Arrakis entscheidet das kostbare Gewürz über Macht, Glauben und das Schicksal eines jungen Erben.',
      en: 'On the desert world Arrakis, the precious spice decides power, faith and the fate of a young heir.',
    },
    query: { title: 'Dune', author: 'Frank Herbert' },
  },
  {
    title: '1984',
    author: 'George Orwell',
    genre: 'Science-Fiction',
    price: 9.0,
    rating: 4.7,
    likeCount: 7100,
    pageCount: 352,
    tags: ['Dystopie', 'Überwachung', 'Klassiker'],
    description: {
      de: 'In einem totalitären Staat wagt Winston Smith das Verbotene: einen eigenen Gedanken.',
      en: 'In a totalitarian state, Winston Smith dares the forbidden — a thought of his own.',
    },
    query: { title: '1984', author: 'Orwell' },
  },
  {
    title: 'Ready Player One',
    author: 'Ernest Cline',
    genre: 'Science-Fiction',
    price: 12.0,
    rating: 4.4,
    likeCount: 3890,
    pageCount: 544,
    tags: ['Virtual Reality', '80er', 'Abenteuer'],
    description: {
      de: 'In einer virtuellen Welt jagt ein Teenager nach einem Erbe, das über die Zukunft der Menschheit entscheidet.',
      en: 'Inside a vast virtual world, a teenager hunts an Easter egg that could reshape humanity’s future.',
    },
    query: { title: 'Ready Player One', author: 'Cline' },
  },
  {
    title: 'Die Tribute von Panem – Tödliche Spiele',
    author: 'Suzanne Collins',
    genre: 'Science-Fiction',
    price: 11.0,
    rating: 4.5,
    likeCount: 6900,
    pageCount: 416,
    tags: ['Dystopie', 'Jugend', 'Rebellion'],
    description: {
      de: 'Katniss meldet sich freiwillig für ein tödliches Spiel, das im ganzen Land live übertragen wird.',
      en: 'Katniss volunteers for a deadly televised game and becomes the spark of a rebellion.',
    },
    query: { title: 'The Hunger Games', author: 'Collins' },
  },
  // ── Thriller ───────────────────────────────────────────────
  {
    title: 'Das Schweigen der Lämmer',
    author: 'Thomas Harris',
    genre: 'Thriller',
    price: 12.0,
    rating: 4.6,
    likeCount: 4100,
    pageCount: 448,
    tags: ['Psychothriller', 'FBI', 'Kult'],
    description: {
      de: 'Eine junge FBI-Agentin sucht Rat beim genialen Kannibalen Hannibal Lecter, um einen Serienmörder zu fassen.',
      en: 'A young FBI trainee bargains with the brilliant cannibal Hannibal Lecter to catch a serial killer.',
    },
    query: { title: 'The Silence of the Lambs', author: 'Harris' },
  },
  {
    title: 'Gone Girl – Das perfekte Opfer',
    author: 'Gillian Flynn',
    genre: 'Thriller',
    price: 11.0,
    rating: 4.4,
    likeCount: 3760,
    pageCount: 576,
    tags: ['Psychothriller', 'Ehe', 'Wendung'],
    description: {
      de: 'Als Amy spurlos verschwindet, gerät ihr Mann unter Verdacht – und nichts ist, wie es scheint.',
      en: 'When Amy vanishes, her husband falls under suspicion — and nothing is what it seems.',
    },
    query: { title: 'Gone Girl', author: 'Flynn' },
  },
  {
    title: 'Verblendung',
    author: 'Stieg Larsson',
    genre: 'Thriller',
    price: 13.0,
    rating: 4.5,
    likeCount: 4200,
    pageCount: 704,
    tags: ['Skandinavien', 'Ermittlung', 'Hacker'],
    description: {
      de: 'Ein Journalist und die Hackerin Lisbeth Salander rollen einen jahrzehntealten Vermisstenfall auf.',
      en: 'A journalist and the hacker Lisbeth Salander reopen a decades-old disappearance.',
    },
    query: { title: 'The Girl with the Dragon Tattoo' },
  },
  {
    title: 'Shutter Island',
    author: 'Dennis Lehane',
    genre: 'Thriller',
    price: 11.0,
    rating: 4.4,
    likeCount: 2650,
    pageCount: 432,
    tags: ['Psychothriller', 'Insel', 'Wendung'],
    description: {
      de: 'Zwei Marshals ermitteln auf einer abgeschotteten Gefängnisinsel – und verlieren den Boden unter den Füßen.',
      en: 'Two marshals investigate a locked-down island asylum and lose their grip on what is real.',
    },
    query: { title: 'Shutter Island', author: 'Lehane' },
  },
  {
    title: 'Sakrileg – The Da Vinci Code',
    author: 'Dan Brown',
    genre: 'Thriller',
    price: 12.0,
    rating: 4.0,
    likeCount: 5200,
    pageCount: 608,
    tags: ['Verschwörung', 'Kunst', 'Rätsel'],
    description: {
      de: 'Ein Mord im Louvre führt den Symbolforscher Robert Langdon auf die Spur eines jahrhundertealten Geheimnisses.',
      en: 'A murder in the Louvre sends symbologist Robert Langdon chasing a centuries-old secret.',
    },
    query: { title: 'The Da Vinci Code', author: 'Brown' },
  },
  // ── Sachbuch ───────────────────────────────────────────────
  {
    title: 'Eine kurze Geschichte der Zeit',
    author: 'Stephen Hawking',
    genre: 'Sachbuch',
    price: 14.0,
    rating: 4.5,
    likeCount: 3900,
    pageCount: 256,
    tags: ['Physik', 'Kosmos', 'Wissenschaft'],
    description: {
      de: 'Vom Urknall bis zu schwarzen Löchern – Hawking erklärt das Universum für alle, die fragen wollen.',
      en: 'From the Big Bang to black holes, Hawking explains the universe for everyone who dares to ask.',
    },
    query: { title: 'A Brief History of Time', author: 'Hawking' },
  },
  {
    title: 'Sapiens – Eine kurze Geschichte der Menschheit',
    author: 'Yuval Noah Harari',
    genre: 'Sachbuch',
    price: 18.0,
    rating: 4.6,
    likeCount: 7400,
    pageCount: 528,
    tags: ['Geschichte', 'Anthropologie', 'Bestseller'],
    description: {
      de: 'Wie wurde aus einem unscheinbaren Affen der Herrscher der Erde? Eine kühne Geschichte der Menschheit.',
      en: 'How did an unremarkable ape come to rule the planet? A bold history of humankind.',
    },
    query: { title: 'Sapiens', author: 'Harari' },
  },
  {
    title: 'Schnelles Denken, langsames Denken',
    author: 'Daniel Kahneman',
    genre: 'Sachbuch',
    price: 16.0,
    rating: 4.4,
    likeCount: 4300,
    pageCount: 624,
    tags: ['Psychologie', 'Entscheidungen', 'Denken'],
    description: {
      de: 'Der Nobelpreisträger zeigt, wie zwei Denksysteme unser Urteilen lenken – und täuschen.',
      en: 'The Nobel laureate reveals the two systems that drive — and deceive — how we think.',
    },
    query: { title: 'Thinking, Fast and Slow', author: 'Kahneman' },
  },
  {
    title: 'Die Kunst des klaren Denkens',
    author: 'Rolf Dobelli',
    genre: 'Sachbuch',
    price: 12.0,
    rating: 4.2,
    likeCount: 2600,
    pageCount: 248,
    tags: ['Denkfehler', 'Ratgeber', 'Psychologie'],
    description: {
      de: '52 Denkfehler, die jeder macht – und wie man sie elegant umgeht.',
      en: '52 thinking errors we all make — and how to sidestep them with ease.',
    },
    query: { title: 'The Art of Thinking Clearly', author: 'Dobelli' },
  },
  {
    title: 'Factfulness',
    author: 'Hans Rosling',
    genre: 'Sachbuch',
    price: 13.0,
    rating: 4.6,
    likeCount: 3100,
    pageCount: 400,
    tags: ['Statistik', 'Weltbild', 'Optimismus'],
    description: {
      de: 'Warum die Welt besser ist, als wir denken – und wie wir lernen, in Fakten statt Ängsten zu denken.',
      en: 'Why the world is better than we think — and how to reason with facts instead of fear.',
    },
    query: { title: 'Factfulness', author: 'Rosling' },
  },
  {
    title: 'Der Junge, der Maulwurf, der Fuchs und das Pferd',
    author: 'Charlie Mackesy',
    genre: 'Sachbuch',
    price: 20.0,
    rating: 4.8,
    likeCount: 5600,
    pageCount: 128,
    tags: ['Illustriert', 'Achtsamkeit', 'Geschenk'],
    description: {
      de: 'Vier ungleiche Freunde und ihre Gespräche über Mut, Freundschaft und das Nachhausekommen.',
      en: 'Four unlikely friends and their gentle conversations about courage, kindness and coming home.',
    },
    query: { title: 'The Boy, the Mole, the Fox and the Horse', author: 'Mackesy' },
  },
];
