import type { Genre } from '../src/app/core/models/book';

/** Hand-curated editorial layer. Open Library supplies cover/isbn/year at build
 *  time (scripts/fetch-seed.ts); everything here is the part a shop owner writes. */
export interface CuratedBook {
  title: string;
  author: string;
  genre: Genre;
  price: number;
  rating: number;
  likeCount: number;
  pageCount: number;
  tags: string[];
  description: { de: string; en: string };
  /** Overrides for the Open Library lookup when the display title differs. */
  query?: { title: string; author?: string };
}

export const curatedBooks: CuratedBook[] = [
  // ── Fantasy ────────────────────────────────────────────────
  {
    title: 'Die unendliche Geschichte',
    author: 'Michael Ende',
    genre: 'Fantasy',
    price: 16.99,
    rating: 4.8,
    likeCount: 4210,
    pageCount: 480,
    tags: ['Klassiker', 'Abenteuer', 'Phantásien', 'Kindheit'],
    description: {
      de: 'Bastian flüchtet sich in ein Buch – und wird selbst Teil der Rettung des untergehenden Reiches Phantásien.',
      en: 'Bastian escapes into a book and becomes the only hope for the vanishing realm of Fantastica.',
    },
  },
  {
    title: 'Momo',
    author: 'Michael Ende',
    genre: 'Fantasy',
    price: 14.0,
    rating: 4.7,
    likeCount: 3105,
    pageCount: 304,
    tags: ['Klassiker', 'Zeit', 'Freundschaft'],
    description: {
      de: 'Ein Mädchen mit der Gabe des Zuhörens stellt sich den grauen Herren, die den Menschen ihre Zeit stehlen.',
      en: 'A girl who truly listens takes on the grey men stealing humanity’s time.',
    },
  },
  {
    title: 'Tintenherz',
    author: 'Cornelia Funke',
    genre: 'Fantasy',
    price: 12.99,
    rating: 4.5,
    likeCount: 2540,
    pageCount: 576,
    tags: ['Bücher', 'Abenteuer', 'Jugend'],
    description: {
      de: 'Meggies Vater kann Figuren aus Büchern herauslesen – bis ein Schurke der Wirklichkeit entkommt.',
      en: 'Meggie’s father can read characters out of books — until a villain escapes into the real world.',
    },
  },
  {
    title: 'Der Herr der Ringe',
    author: 'J. R. R. Tolkien',
    genre: 'Fantasy',
    price: 28.0,
    rating: 4.9,
    likeCount: 8800,
    pageCount: 1280,
    tags: ['Epos', 'Mittelerde', 'Klassiker'],
    description: {
      de: 'Ein Hobbit trägt den Einen Ring quer durch Mittelerde, um die Macht des Dunklen Herrschers zu brechen.',
      en: 'A hobbit carries the One Ring across Middle-earth to unmake the Dark Lord’s power.',
    },
    query: { title: 'The Lord of the Rings', author: 'Tolkien' },
  },
  {
    title: 'Harry Potter und der Stein der Weisen',
    author: 'J. K. Rowling',
    genre: 'Fantasy',
    price: 9.99,
    rating: 4.8,
    likeCount: 9600,
    pageCount: 336,
    tags: ['Zauberei', 'Internat', 'Jugend'],
    description: {
      de: 'Ein Waisenjunge erfährt an seinem elften Geburtstag, dass er ein Zauberer ist – und ein Schicksal hat.',
      en: 'On his eleventh birthday an orphan learns he is a wizard — and that destiny awaits at Hogwarts.',
    },
    query: { title: "Harry Potter and the Philosopher's Stone", author: 'Rowling' },
  },
  {
    title: 'Der Name des Windes',
    author: 'Patrick Rothfuss',
    genre: 'Fantasy',
    price: 15.0,
    rating: 4.6,
    likeCount: 3320,
    pageCount: 864,
    tags: ['Magie', 'Musik', 'Erzählung'],
    description: {
      de: 'Der berüchtigte Kvothe erzählt selbst, wie aus einem Gauklerkind eine Legende wurde.',
      en: 'The infamous Kvothe recounts how a travelling player’s child became a living legend.',
    },
    query: { title: 'The Name of the Wind', author: 'Rothfuss' },
  },
  // ── Romantik ───────────────────────────────────────────────
  {
    title: 'Stolz und Vorurteil',
    author: 'Jane Austen',
    genre: 'Romantik',
    price: 8.0,
    rating: 4.7,
    likeCount: 6100,
    pageCount: 480,
    tags: ['Klassiker', 'England', 'Gesellschaft'],
    description: {
      de: 'Elizabeth Bennet und der hochmütige Mr. Darcy ringen zwischen Vorurteil und wachsender Zuneigung.',
      en: 'Elizabeth Bennet and the proud Mr Darcy spar their way from prejudice to love.',
    },
    query: { title: 'Pride and Prejudice', author: 'Austen' },
  },
  {
    title: 'Wie ein einziger Tag',
    author: 'Nicholas Sparks',
    genre: 'Romantik',
    price: 11.0,
    rating: 4.3,
    likeCount: 2870,
    pageCount: 256,
    tags: ['Liebe', 'Erinnerung', 'Drama'],
    description: {
      de: 'Eine große Liebe trotzt der Zeit – und einer Krankheit, die alle Erinnerung auszulöschen droht.',
      en: 'A lifelong love endures against time and an illness threatening to erase every memory.',
    },
    query: { title: 'The Notebook', author: 'Sparks' },
  },
  {
    title: 'Vom Winde verweht',
    author: 'Margaret Mitchell',
    genre: 'Romantik',
    price: 13.5,
    rating: 4.4,
    likeCount: 3450,
    pageCount: 1024,
    tags: ['Klassiker', 'Epos', 'Südstaaten'],
    description: {
      de: 'Scarlett O’Hara kämpft im zerfallenden Süden um Land, Liebe und das eigene Überleben.',
      en: 'Scarlett O’Hara fights for land, love and survival in the collapsing American South.',
    },
    query: { title: 'Gone with the Wind', author: 'Mitchell' },
  },
  {
    title: 'Der Vorleser',
    author: 'Bernhard Schlink',
    genre: 'Romantik',
    price: 10.0,
    rating: 4.2,
    likeCount: 1980,
    pageCount: 208,
    tags: ['Nachkriegszeit', 'Schuld', 'Deutschland'],
    description: {
      de: 'Eine Affäre zwischen einem Jungen und einer älteren Frau führt Jahre später in einen Kriegsverbrecherprozess.',
      en: 'A teenager’s affair with an older woman resurfaces years later in a war-crimes trial.',
    },
    query: { title: 'Der Vorleser', author: 'Schlink' },
  },
  {
    title: 'Schokolade zum Frühstück',
    author: 'Marian Keyes',
    genre: 'Romantik',
    price: 11.0,
    rating: 4.1,
    likeCount: 1420,
    pageCount: 624,
    tags: ['Humor', 'Familie', 'Neuanfang'],
    description: {
      de: 'Nach dem Ende ihrer Ehe sucht Rachel zwischen Chaos und Komik einen Weg zurück ins Leben.',
      en: 'After her marriage falls apart, Rachel finds her way back to life through chaos and comedy.',
    },
    query: { title: 'Rachel’s Holiday', author: 'Marian Keyes' },
  },
  // ── Science-Fiction ────────────────────────────────────────
  {
    title: 'Per Anhalter durch die Galaxis',
    author: 'Douglas Adams',
    genre: 'Science-Fiction',
    price: 12.0,
    rating: 4.7,
    likeCount: 5400,
    pageCount: 256,
    tags: ['Humor', 'Weltraum', 'Kult'],
    description: {
      de: 'Kurz vor der Sprengung der Erde wird Arthur Dent ins absurdeste Abenteuer der Galaxis gerissen.',
      en: 'Moments before Earth is demolished, Arthur Dent is swept into the galaxy’s most absurd adventure.',
    },
    query: { title: "The Hitchhiker's Guide to the Galaxy", author: 'Adams' },
  },
  {
    title: 'Der Marsianer',
    author: 'Andy Weir',
    genre: 'Science-Fiction',
    price: 13.0,
    rating: 4.6,
    likeCount: 4720,
    pageCount: 416,
    tags: ['Mars', 'Survival', 'Wissenschaft'],
    description: {
      de: 'Allein auf dem Mars zurückgelassen, kämpft ein Astronaut mit Ingenieurskunst und Humor ums Überleben.',
      en: 'Stranded alone on Mars, an astronaut science-and-jokes his way toward survival.',
    },
    query: { title: 'The Martian', author: 'Weir' },
  },
  {
    title: 'Dune – Der Wüstenplanet',
    author: 'Frank Herbert',
    genre: 'Science-Fiction',
    price: 16.0,
    rating: 4.7,
    likeCount: 6300,
    pageCount: 816,
    tags: ['Epos', 'Politik', 'Wüste'],
    description: {
      de: 'Auf dem Wüstenplaneten Arrakis entscheidet das kostbare Gewürz über Macht, Glauben und das Schicksal eines jungen Erben.',
      en: 'On the desert world Arrakis, the precious spice decides power, faith and the fate of a young heir.',
    },
    query: { title: 'Dune', author: 'Frank Herbert' },
  },
  {
    title: '1984',
    author: 'George Orwell',
    genre: 'Science-Fiction',
    price: 9.0,
    rating: 4.7,
    likeCount: 7100,
    pageCount: 352,
    tags: ['Dystopie', 'Überwachung', 'Klassiker'],
    description: {
      de: 'In einem totalitären Staat wagt Winston Smith das Verbotene: einen eigenen Gedanken.',
      en: 'In a totalitarian state, Winston Smith dares the forbidden — a thought of his own.',
    },
    query: { title: '1984', author: 'Orwell' },
  },
  {
    title: 'Ready Player One',
    author: 'Ernest Cline',
    genre: 'Science-Fiction',
    price: 12.0,
    rating: 4.4,
    likeCount: 3890,
    pageCount: 544,
    tags: ['Virtual Reality', '80er', 'Abenteuer'],
    description: {
      de: 'In einer virtuellen Welt jagt ein Teenager nach einem Erbe, das über die Zukunft der Menschheit entscheidet.',
      en: 'Inside a vast virtual world, a teenager hunts an Easter egg that could reshape humanity’s future.',
    },
    query: { title: 'Ready Player One', author: 'Cline' },
  },
  {
    title: 'Die Tribute von Panem – Tödliche Spiele',
    author: 'Suzanne Collins',
    genre: 'Science-Fiction',
    price: 11.0,
    rating: 4.5,
    likeCount: 6900,
    pageCount: 416,
    tags: ['Dystopie', 'Jugend', 'Rebellion'],
    description: {
      de: 'Katniss meldet sich freiwillig für ein tödliches Spiel, das im ganzen Land live übertragen wird.',
      en: 'Katniss volunteers for a deadly televised game and becomes the spark of a rebellion.',
    },
    query: { title: 'The Hunger Games', author: 'Collins' },
  },
  // ── Thriller ───────────────────────────────────────────────
  {
    title: 'Das Schweigen der Lämmer',
    author: 'Thomas Harris',
    genre: 'Thriller',
    price: 12.0,
    rating: 4.6,
    likeCount: 4100,
    pageCount: 448,
    tags: ['Psychothriller', 'FBI', 'Kult'],
    description: {
      de: 'Eine junge FBI-Agentin sucht Rat beim genialen Kannibalen Hannibal Lecter, um einen Serienmörder zu fassen.',
      en: 'A young FBI trainee bargains with the brilliant cannibal Hannibal Lecter to catch a serial killer.',
    },
    query: { title: 'The Silence of the Lambs', author: 'Harris' },
  },
  {
    title: 'Gone Girl – Das perfekte Opfer',
    author: 'Gillian Flynn',
    genre: 'Thriller',
    price: 11.0,
    rating: 4.4,
    likeCount: 3760,
    pageCount: 576,
    tags: ['Psychothriller', 'Ehe', 'Wendung'],
    description: {
      de: 'Als Amy spurlos verschwindet, gerät ihr Mann unter Verdacht – und nichts ist, wie es scheint.',
      en: 'When Amy vanishes, her husband falls under suspicion — and nothing is what it seems.',
    },
    query: { title: 'Gone Girl', author: 'Flynn' },
  },
  {
    title: 'Verblendung',
    author: 'Stieg Larsson',
    genre: 'Thriller',
    price: 13.0,
    rating: 4.5,
    likeCount: 4200,
    pageCount: 704,
    tags: ['Skandinavien', 'Ermittlung', 'Hacker'],
    description: {
      de: 'Ein Journalist und die Hackerin Lisbeth Salander rollen einen jahrzehntealten Vermisstenfall auf.',
      en: 'A journalist and the hacker Lisbeth Salander reopen a decades-old disappearance.',
    },
    query: { title: 'The Girl with the Dragon Tattoo' },
  },
  {
    title: 'Shutter Island',
    author: 'Dennis Lehane',
    genre: 'Thriller',
    price: 11.0,
    rating: 4.4,
    likeCount: 2650,
    pageCount: 432,
    tags: ['Psychothriller', 'Insel', 'Wendung'],
    description: {
      de: 'Zwei Marshals ermitteln auf einer abgeschotteten Gefängnisinsel – und verlieren den Boden unter den Füßen.',
      en: 'Two marshals investigate a locked-down island asylum and lose their grip on what is real.',
    },
    query: { title: 'Shutter Island', author: 'Lehane' },
  },
  {
    title: 'Sakrileg – The Da Vinci Code',
    author: 'Dan Brown',
    genre: 'Thriller',
    price: 12.0,
    rating: 4.0,
    likeCount: 5200,
    pageCount: 608,
    tags: ['Verschwörung', 'Kunst', 'Rätsel'],
    description: {
      de: 'Ein Mord im Louvre führt den Symbolforscher Robert Langdon auf die Spur eines jahrhundertealten Geheimnisses.',
      en: 'A murder in the Louvre sends symbologist Robert Langdon chasing a centuries-old secret.',
    },
    query: { title: 'The Da Vinci Code', author: 'Brown' },
  },
  // ── Sachbuch ───────────────────────────────────────────────
  {
    title: 'Eine kurze Geschichte der Zeit',
    author: 'Stephen Hawking',
    genre: 'Sachbuch',
    price: 14.0,
    rating: 4.5,
    likeCount: 3900,
    pageCount: 256,
    tags: ['Physik', 'Kosmos', 'Wissenschaft'],
    description: {
      de: 'Vom Urknall bis zu schwarzen Löchern – Hawking erklärt das Universum für alle, die fragen wollen.',
      en: 'From the Big Bang to black holes, Hawking explains the universe for everyone who dares to ask.',
    },
    query: { title: 'A Brief History of Time', author: 'Hawking' },
  },
  {
    title: 'Sapiens – Eine kurze Geschichte der Menschheit',
    author: 'Yuval Noah Harari',
    genre: 'Sachbuch',
    price: 18.0,
    rating: 4.6,
    likeCount: 7400,
    pageCount: 528,
    tags: ['Geschichte', 'Anthropologie', 'Bestseller'],
    description: {
      de: 'Wie wurde aus einem unscheinbaren Affen der Herrscher der Erde? Eine kühne Geschichte der Menschheit.',
      en: 'How did an unremarkable ape come to rule the planet? A bold history of humankind.',
    },
    query: { title: 'Sapiens', author: 'Harari' },
  },
  {
    title: 'Schnelles Denken, langsames Denken',
    author: 'Daniel Kahneman',
    genre: 'Sachbuch',
    price: 16.0,
    rating: 4.4,
    likeCount: 4300,
    pageCount: 624,
    tags: ['Psychologie', 'Entscheidungen', 'Denken'],
    description: {
      de: 'Der Nobelpreisträger zeigt, wie zwei Denksysteme unser Urteilen lenken – und täuschen.',
      en: 'The Nobel laureate reveals the two systems that drive — and deceive — how we think.',
    },
    query: { title: 'Thinking, Fast and Slow', author: 'Kahneman' },
  },
  {
    title: 'Die Kunst des klaren Denkens',
    author: 'Rolf Dobelli',
    genre: 'Sachbuch',
    price: 12.0,
    rating: 4.2,
    likeCount: 2600,
    pageCount: 248,
    tags: ['Denkfehler', 'Ratgeber', 'Psychologie'],
    description: {
      de: '52 Denkfehler, die jeder macht – und wie man sie elegant umgeht.',
      en: '52 thinking errors we all make — and how to sidestep them with ease.',
    },
    query: { title: 'The Art of Thinking Clearly', author: 'Dobelli' },
  },
  {
    title: 'Factfulness',
    author: 'Hans Rosling',
    genre: 'Sachbuch',
    price: 13.0,
    rating: 4.6,
    likeCount: 3100,
    pageCount: 400,
    tags: ['Statistik', 'Weltbild', 'Optimismus'],
    description: {
      de: 'Warum die Welt besser ist, als wir denken – und wie wir lernen, in Fakten statt Ängsten zu denken.',
      en: 'Why the world is better than we think — and how to reason with facts instead of fear.',
    },
    query: { title: 'Factfulness', author: 'Rosling' },
  },
  {
    title: 'Der Junge, der Maulwurf, der Fuchs und das Pferd',
    author: 'Charlie Mackesy',
    genre: 'Sachbuch',
    price: 20.0,
    rating: 4.8,
    likeCount: 5600,
    pageCount: 128,
    tags: ['Illustriert', 'Achtsamkeit', 'Geschenk'],
    description: {
      de: 'Vier ungleiche Freunde und ihre Gespräche über Mut, Freundschaft und das Nachhausekommen.',
      en: 'Four unlikely friends and their gentle conversations about courage, kindness and coming home.',
    },
    query: { title: 'The Boy, the Mole, the Fox and the Horse', author: 'Mackesy' },
  },

  // ── Fantasy (Erweiterung) ──────────────────────────────────
  {
    title: 'Der Hobbit',
    author: 'J. R. R. Tolkien',
    genre: 'Fantasy',
    price: 14.0,
    rating: 4.8,
    likeCount: 7400,
    pageCount: 416,
    tags: ['Mittelerde', 'Abenteuer', 'Klassiker'],
    description: {
      de: 'Bilbo Beutlin wird aus seiner Höhle gelockt und findet zwischen Trollen, Drachen und einem Ring sein Abenteuer.',
      en: 'Bilbo Baggins is swept out of his hobbit-hole into an adventure of trolls, dragons and one fateful ring.',
    },
    query: { title: 'The Hobbit', author: 'Tolkien' },
  },
  {
    title: 'Die Herren von Winterfell',
    author: 'George R. R. Martin',
    genre: 'Fantasy',
    price: 18.0,
    rating: 4.7,
    likeCount: 6900,
    pageCount: 576,
    tags: ['Epos', 'Intrigen', 'Westeros'],
    description: {
      de: 'Im Ringen um den Eisernen Thron sind Ehre und Loyalität die gefährlichsten Schwächen.',
      en: 'In the game for the Iron Throne, honour and loyalty are the deadliest weaknesses.',
    },
    query: { title: 'A Game of Thrones', author: 'George R. R. Martin' },
  },
  {
    title: 'Der König von Narnia',
    author: 'C. S. Lewis',
    genre: 'Fantasy',
    price: 10.0,
    rating: 4.6,
    likeCount: 3900,
    pageCount: 208,
    tags: ['Klassiker', 'Kindheit', 'Wintermärchen'],
    description: {
      de: 'Vier Geschwister treten durch einen Kleiderschrank in ein verzaubertes Land im ewigen Winter.',
      en: 'Four siblings step through a wardrobe into an enchanted land trapped in eternal winter.',
    },
    query: { title: 'The Lion, the Witch and the Wardrobe', author: 'C. S. Lewis' },
  },
  {
    title: 'Eragon – Das Vermächtnis der Drachenreiter',
    author: 'Christopher Paolini',
    genre: 'Fantasy',
    price: 12.0,
    rating: 4.3,
    likeCount: 2800,
    pageCount: 736,
    tags: ['Drachen', 'Jugend', 'Abenteuer'],
    description: {
      de: 'Ein Bauernjunge findet ein Drachenei – und wird zum letzten Hoffnungsträger gegen einen tyrannischen König.',
      en: 'A farm boy finds a dragon egg and becomes the last hope against a tyrant king.',
    },
    query: { title: 'Eragon', author: 'Paolini' },
  },
  {
    title: 'Die Zwerge',
    author: 'Markus Heitz',
    genre: 'Fantasy',
    price: 13.0,
    rating: 4.4,
    likeCount: 2100,
    pageCount: 544,
    tags: ['Zwerge', 'Schlachten', 'Deutsche Fantasy'],
    description: {
      de: 'Tungdil, bei Menschen aufgewachsen, muss beweisen, was wirklich in einem Zwerg steckt.',
      en: 'Raised among humans, Tungdil must prove what truly lives in the heart of a dwarf.',
    },
    query: { title: 'The Dwarves', author: 'Markus Heitz' },
  },
  {
    title: 'Rubinrot',
    author: 'Kerstin Gier',
    genre: 'Fantasy',
    price: 11.0,
    rating: 4.2,
    likeCount: 1900,
    pageCount: 352,
    tags: ['Zeitreise', 'Jugend', 'Liebe'],
    description: {
      de: 'Gwendolyn springt unfreiwillig durch die Zeit – und mitten hinein in ein gefährliches Familiengeheimnis.',
      en: 'Gwendolyn tumbles through time — straight into a dangerous family secret.',
    },
    query: { title: 'Ruby Red', author: 'Kerstin Gier' },
  },
  {
    title: 'Der letzte Wunsch',
    author: 'Andrzej Sapkowski',
    genre: 'Fantasy',
    price: 12.0,
    rating: 4.5,
    likeCount: 3300,
    pageCount: 384,
    tags: ['Witcher', 'Monster', 'Kurzgeschichten'],
    description: {
      de: 'Hexer Geralt von Riva jagt Monster – doch die wahren Ungeheuer sind oft die Menschen.',
      en: 'Witcher Geralt of Rivia hunts monsters — but the real beasts are often human.',
    },
    query: { title: 'The Last Wish', author: 'Sapkowski' },
  },
  {
    title: 'Der Alchimist',
    author: 'Paulo Coelho',
    genre: 'Fantasy',
    price: 12.0,
    rating: 4.3,
    likeCount: 5100,
    pageCount: 224,
    tags: ['Fabel', 'Lebensweg', 'Wüste'],
    description: {
      de: 'Der Hirte Santiago folgt einem wiederkehrenden Traum bis zu den Pyramiden – und zu sich selbst.',
      en: 'Shepherd Santiago follows a recurring dream to the pyramids — and to himself.',
    },
    query: { title: 'The Alchemist', author: 'Coelho' },
  },
  {
    title: 'Die Stadt der Träumenden Bücher',
    author: 'Walter Moers',
    genre: 'Fantasy',
    price: 16.0,
    rating: 4.6,
    likeCount: 2700,
    pageCount: 496,
    tags: ['Zamonien', 'Bücher', 'Humor'],
    description: {
      de: 'Hildegunst von Mythenmetz steigt in die Katakomben von Buchhaim – wo Bücher träumen und töten.',
      en: 'Optimus Yarnspinner descends into the catacombs of Bookholm, where books dream and kill.',
    },
    query: { title: 'The City of Dreaming Books', author: 'Walter Moers' },
  },
  {
    title: 'Percy Jackson – Diebe im Olymp',
    author: 'Rick Riordan',
    genre: 'Fantasy',
    price: 10.0,
    rating: 4.4,
    likeCount: 3100,
    pageCount: 448,
    tags: ['Mythologie', 'Jugend', 'Humor'],
    description: {
      de: 'Percy erfährt, dass sein Vater ein griechischer Gott ist – und Zeus’ Blitz gestohlen wurde.',
      en: 'Percy learns his father is a Greek god — and that Zeus’ master bolt has been stolen.',
    },
    query: { title: 'The Lightning Thief', author: 'Rick Riordan' },
  },

  // ── Romantik (Erweiterung) ─────────────────────────────────
  {
    title: 'Gut gegen Nordwind',
    author: 'Daniel Glattauer',
    genre: 'Romantik',
    price: 11.0,
    rating: 4.3,
    likeCount: 2300,
    pageCount: 224,
    tags: ['E-Mail-Roman', 'Modern', 'Wien'],
    description: {
      de: 'Eine falsch adressierte E-Mail wird zum Beginn einer Liebe, die nur aus Worten besteht.',
      en: 'A misaddressed email sparks a love affair made entirely of words.',
    },
    query: { title: 'Love Virtually', author: 'Daniel Glattauer' },
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    genre: 'Romantik',
    price: 9.0,
    rating: 4.6,
    likeCount: 4400,
    pageCount: 592,
    tags: ['Klassiker', 'Gothic', 'Selbstbestimmung'],
    description: {
      de: 'Eine Gouvernante mit eisernem Willen verliebt sich in einen Mann mit einem dunklen Geheimnis.',
      en: 'A governess of iron will falls for a man with a dark secret in his attic.',
    },
    query: { title: 'Jane Eyre', author: 'Charlotte Bronte' },
  },
  {
    title: 'Sturmhöhe',
    author: 'Emily Brontë',
    genre: 'Romantik',
    price: 9.0,
    rating: 4.4,
    likeCount: 3600,
    pageCount: 528,
    tags: ['Klassiker', 'Moor', 'Besessenheit'],
    description: {
      de: 'Heathcliff und Catherine – eine Liebe wie das Moor: wild, dunkel und unbarmherzig.',
      en: 'Heathcliff and Catherine — a love like the moors: wild, dark and merciless.',
    },
    query: { title: 'Wuthering Heights', author: 'Emily Bronte' },
  },
  {
    title: 'Die Liebe in den Zeiten der Cholera',
    author: 'Gabriel García Márquez',
    genre: 'Romantik',
    price: 14.0,
    rating: 4.5,
    likeCount: 3000,
    pageCount: 512,
    tags: ['Klassiker', 'Lateinamerika', 'Lebenslang'],
    description: {
      de: 'Florentino wartet einundfünfzig Jahre, neun Monate und vier Tage auf seine große Liebe.',
      en: 'Florentino waits fifty-one years, nine months and four days for his one great love.',
    },
    query: { title: 'Love in the Time of Cholera', author: 'Garcia Marquez' },
  },
  {
    title: 'Ein ganzes halbes Jahr',
    author: 'Jojo Moyes',
    genre: 'Romantik',
    price: 12.0,
    rating: 4.5,
    likeCount: 5200,
    pageCount: 512,
    tags: ['Tränen', 'Modern', 'Bestseller'],
    description: {
      de: 'Lou soll Will nur pflegen – doch sie bringt ihm das Leben zurück, und er ihr den Mut.',
      en: 'Lou is hired to care for Will — instead she brings him back to life, and he gives her courage.',
    },
    query: { title: 'Me Before You', author: 'Jojo Moyes' },
  },
  {
    title: 'P.S. Ich liebe Dich',
    author: 'Cecelia Ahern',
    genre: 'Romantik',
    price: 11.0,
    rating: 4.2,
    likeCount: 3400,
    pageCount: 432,
    tags: ['Briefe', 'Trauer', 'Neuanfang'],
    description: {
      de: 'Gerry ist tot – aber seine Briefe führen Holly Monat für Monat zurück ins Leben.',
      en: 'Gerry is gone — but his letters guide Holly back to life, one month at a time.',
    },
    query: { title: 'PS, I Love You', author: 'Cecelia Ahern' },
  },
  {
    title: 'Naokos Lächeln',
    author: 'Haruki Murakami',
    genre: 'Romantik',
    price: 12.0,
    rating: 4.3,
    likeCount: 2600,
    pageCount: 416,
    tags: ['Japan', 'Melancholie', 'Coming-of-Age'],
    description: {
      de: 'Toru zwischen zwei Frauen, Tokio Ende der Sechziger – und der Frage, was Erinnerung mit uns macht.',
      en: 'Toru, two women, late-sixties Tokyo — and what memory does to us.',
    },
    query: { title: 'Norwegian Wood', author: 'Haruki Murakami' },
  },
  {
    title: 'Anna Karenina',
    author: 'Lew Tolstoi',
    genre: 'Romantik',
    price: 16.0,
    rating: 4.5,
    likeCount: 3800,
    pageCount: 1024,
    tags: ['Klassiker', 'Russland', 'Gesellschaft'],
    description: {
      de: 'Eine verheiratete Frau folgt ihrer Leidenschaft – und die Gesellschaft stellt ihr die Rechnung.',
      en: 'A married woman follows her passion — and society makes her pay the price.',
    },
    query: { title: 'Anna Karenina', author: 'Tolstoy' },
  },
  {
    title: 'Der große Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Romantik',
    price: 10.0,
    rating: 4.3,
    likeCount: 4100,
    pageCount: 240,
    tags: ['Klassiker', 'Zwanziger', 'Amerikanischer Traum'],
    description: {
      de: 'Gatsby feiert rauschende Feste für eine Liebe, die längst Vergangenheit ist.',
      en: 'Gatsby throws glittering parties for a love that already belongs to the past.',
    },
    query: { title: 'The Great Gatsby', author: 'Fitzgerald' },
  },
  {
    title: 'Emma',
    author: 'Jane Austen',
    genre: 'Romantik',
    price: 9.0,
    rating: 4.4,
    likeCount: 2900,
    pageCount: 512,
    tags: ['Klassiker', 'Verkupplung', 'Witz'],
    description: {
      de: 'Emma verkuppelt halb Highbury – nur ihr eigenes Herz hat sie nicht auf der Rechnung.',
      en: 'Emma matchmakes half of Highbury — forgetting to account for her own heart.',
    },
    query: { title: 'Emma', author: 'Jane Austen' },
  },

  // ── Science-Fiction (Erweiterung) ──────────────────────────
  {
    title: 'Schöne neue Welt',
    author: 'Aldous Huxley',
    genre: 'Science-Fiction',
    price: 11.0,
    rating: 4.4,
    likeCount: 4300,
    pageCount: 368,
    tags: ['Dystopie', 'Klassiker', 'Gesellschaft'],
    description: {
      de: 'Eine Welt ohne Schmerz, ohne Tiefe, ohne Freiheit – und alle sind glücklich. Fast alle.',
      en: 'A world without pain, depth or freedom — and everyone is happy. Almost everyone.',
    },
    query: { title: 'Brave New World', author: 'Huxley' },
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    genre: 'Science-Fiction',
    price: 10.0,
    rating: 4.4,
    likeCount: 3900,
    pageCount: 272,
    tags: ['Dystopie', 'Bücher', 'Klassiker'],
    description: {
      de: 'Feuerwehrmann Montag verbrennt Bücher – bis er anfängt, eines zu lesen.',
      en: 'Fireman Montag burns books — until the day he starts reading one.',
    },
    query: { title: 'Fahrenheit 451', author: 'Bradbury' },
  },
  {
    title: 'Der Report der Magd',
    author: 'Margaret Atwood',
    genre: 'Science-Fiction',
    price: 12.0,
    rating: 4.5,
    likeCount: 4600,
    pageCount: 416,
    tags: ['Dystopie', 'Feminismus', 'Gilead'],
    description: {
      de: 'In der Republik Gilead ist Desfred nur noch eines: ein Körper, der dem Staat gehört.',
      en: 'In the Republic of Gilead, Offred is reduced to one thing: a body owned by the state.',
    },
    query: { title: "The Handmaid's Tale", author: 'Atwood' },
  },
  {
    title: 'Das große Spiel',
    author: 'Orson Scott Card',
    genre: 'Science-Fiction',
    price: 11.0,
    rating: 4.4,
    likeCount: 3200,
    pageCount: 448,
    tags: ['Weltraum', 'Strategie', 'Jugend'],
    description: {
      de: 'Ender Wiggin wird zum perfekten Befehlshaber ausgebildet – für ein Spiel, das keines ist.',
      en: 'Ender Wiggin is trained to be the perfect commander — for a game that is no game.',
    },
    query: { title: "Ender's Game", author: 'Orson Scott Card' },
  },
  {
    title: 'Krieg der Welten',
    author: 'H. G. Wells',
    genre: 'Science-Fiction',
    price: 9.0,
    rating: 4.1,
    likeCount: 2400,
    pageCount: 288,
    tags: ['Klassiker', 'Invasion', 'Mars'],
    description: {
      de: 'Die Marsianer landen in England – und die Krone der Schöpfung wird zur Beute.',
      en: 'The Martians land in England — and the lords of creation become the prey.',
    },
    query: { title: 'The War of the Worlds', author: 'H. G. Wells' },
  },
  {
    title: 'Die Zeitmaschine',
    author: 'H. G. Wells',
    genre: 'Science-Fiction',
    price: 8.0,
    rating: 4.1,
    likeCount: 2200,
    pageCount: 208,
    tags: ['Klassiker', 'Zeitreise', 'Zukunft'],
    description: {
      de: 'Ein Erfinder reist ins Jahr 802.701 – und findet die Zukunft der Menschheit zweigeteilt.',
      en: 'An inventor travels to the year 802,701 and finds humanity split in two.',
    },
    query: { title: 'The Time Machine', author: 'H. G. Wells' },
  },
  {
    title: 'Die Foundation-Trilogie',
    author: 'Isaac Asimov',
    genre: 'Science-Fiction',
    price: 18.0,
    rating: 4.5,
    likeCount: 3500,
    pageCount: 800,
    tags: ['Klassiker', 'Galaktisches Imperium', 'Psychohistorik'],
    description: {
      de: 'Hari Seldon sieht den Fall des Imperiums voraus – und plant das Wissen der Menschheit zu retten.',
      en: 'Hari Seldon foresees the empire’s fall — and plots to save the knowledge of humankind.',
    },
    query: { title: 'Foundation', author: 'Isaac Asimov' },
  },
  {
    title: 'Solaris',
    author: 'Stanisław Lem',
    genre: 'Science-Fiction',
    price: 12.0,
    rating: 4.3,
    likeCount: 2000,
    pageCount: 288,
    tags: ['Klassiker', 'Ozean', 'Erster Kontakt'],
    description: {
      de: 'Ein denkender Ozean spiegelt den Forschern ihre tiefsten Erinnerungen – Kontakt ist unmöglich.',
      en: 'A sentient ocean mirrors the researchers’ deepest memories — contact remains impossible.',
    },
    query: { title: 'Solaris', author: 'Lem' },
  },
  {
    title: 'Der Astronaut',
    author: 'Andy Weir',
    genre: 'Science-Fiction',
    price: 16.0,
    rating: 4.7,
    likeCount: 4800,
    pageCount: 560,
    tags: ['Weltraum', 'Wissenschaft', 'Humor'],
    description: {
      de: 'Ryland Grace erwacht allein im All, ohne Gedächtnis – und mit der Rettung der Erde als Auftrag.',
      en: 'Ryland Grace wakes alone in space with no memory — and Earth’s survival on his to-do list.',
    },
    query: { title: 'Project Hail Mary', author: 'Andy Weir' },
  },
  {
    title: 'Die drei Sonnen',
    author: 'Cixin Liu',
    genre: 'Science-Fiction',
    price: 15.0,
    rating: 4.4,
    likeCount: 3700,
    pageCount: 592,
    tags: ['Erster Kontakt', 'China', 'Physik'],
    description: {
      de: 'Ein Signal ins All wird beantwortet – und die Menschheit erfährt, dass sie nicht allein ist.',
      en: 'A signal sent into space gets an answer — and humanity learns it is not alone.',
    },
    query: { title: 'The Three-Body Problem', author: 'Cixin Liu' },
  },

  // ── Thriller (Erweiterung) ─────────────────────────────────
  {
    title: 'Und dann gabs keines mehr',
    author: 'Agatha Christie',
    genre: 'Thriller',
    price: 10.0,
    rating: 4.5,
    likeCount: 4000,
    pageCount: 272,
    tags: ['Klassiker', 'Insel', 'Whodunit'],
    description: {
      de: 'Zehn Fremde auf einer Insel, ein Kinderreim – und nach jedem Vers ein Toter mehr.',
      en: 'Ten strangers on an island, a nursery rhyme — and one more body after every verse.',
    },
    query: { title: 'And Then There Were None', author: 'Agatha Christie' },
  },
  {
    title: 'Mord im Orientexpress',
    author: 'Agatha Christie',
    genre: 'Thriller',
    price: 10.0,
    rating: 4.4,
    likeCount: 3600,
    pageCount: 256,
    tags: ['Klassiker', 'Poirot', 'Zug'],
    description: {
      de: 'Ein Toter im Schnee festgefahrenen Zug – und zwölf Verdächtige mit perfekten Alibis.',
      en: 'A body on a train stuck in the snow — and twelve suspects with perfect alibis.',
    },
    query: { title: 'Murder on the Orient Express', author: 'Agatha Christie' },
  },
  {
    title: 'Die Therapie',
    author: 'Sebastian Fitzek',
    genre: 'Thriller',
    price: 11.0,
    rating: 4.3,
    likeCount: 3100,
    pageCount: 336,
    tags: ['Psychothriller', 'Deutschland', 'Bestseller'],
    description: {
      de: 'Josys Verschwinden hat keine Zeugen – bis eine Fremde behauptet, seine Geschichte zu kennen.',
      en: 'Josy vanished without witnesses — until a stranger claims to know the whole story.',
    },
    query: { title: 'Therapy', author: 'Sebastian Fitzek' },
  },
  {
    title: 'Passagier 23',
    author: 'Sebastian Fitzek',
    genre: 'Thriller',
    price: 11.0,
    rating: 4.2,
    likeCount: 2700,
    pageCount: 432,
    tags: ['Psychothriller', 'Kreuzfahrt', 'Vermisste'],
    description: {
      de: 'Auf jeder Kreuzfahrt verschwinden Menschen spurlos. Auf der Sultan kehrt eine zurück.',
      en: 'People vanish from cruise ships without a trace. On the Sultan, one comes back.',
    },
    query: { title: 'Passenger 23', author: 'Sebastian Fitzek' },
  },
  {
    title: 'Misery',
    author: 'Stephen King',
    genre: 'Thriller',
    price: 12.0,
    rating: 4.4,
    likeCount: 3300,
    pageCount: 416,
    tags: ['Psychothriller', 'Isolation', 'Fan'],
    description: {
      de: 'Bestsellerautor Paul Sheldon wird von seinem größten Fan gerettet – und gefangen gehalten.',
      en: 'Novelist Paul Sheldon is rescued by his number-one fan — and held captive by her.',
    },
    query: { title: 'Misery', author: 'Stephen King' },
  },
  {
    title: 'Shining',
    author: 'Stephen King',
    genre: 'Thriller',
    price: 12.0,
    rating: 4.5,
    likeCount: 4200,
    pageCount: 512,
    tags: ['Horror', 'Hotel', 'Klassiker'],
    description: {
      de: 'Das Overlook-Hotel im Winter: leer, abgeschnitten – und sehr, sehr wach.',
      en: 'The Overlook Hotel in winter: empty, snowed in — and very much awake.',
    },
    query: { title: 'The Shining', author: 'Stephen King' },
  },
  {
    title: 'Es',
    author: 'Stephen King',
    genre: 'Thriller',
    price: 16.0,
    rating: 4.5,
    likeCount: 4700,
    pageCount: 1536,
    tags: ['Horror', 'Kindheit', 'Derry'],
    description: {
      de: 'Alle 27 Jahre erwacht in Derry etwas, das die Gestalt eurer schlimmsten Angst trägt.',
      en: 'Every 27 years something wakes in Derry wearing the shape of your worst fear.',
    },
    query: { title: 'It', author: 'Stephen King' },
  },
  {
    title: 'Der Pate',
    author: 'Mario Puzo',
    genre: 'Thriller',
    price: 13.0,
    rating: 4.6,
    likeCount: 3800,
    pageCount: 576,
    tags: ['Mafia', 'Familie', 'Klassiker'],
    description: {
      de: 'Don Corleone macht Angebote, die man nicht ablehnen kann – sein Sohn wollte nie dazugehören.',
      en: 'Don Corleone makes offers no one can refuse — his son never wanted in.',
    },
    query: { title: 'The Godfather', author: 'Mario Puzo' },
  },
  {
    title: 'Die Chemie des Todes',
    author: 'Simon Beckett',
    genre: 'Thriller',
    price: 11.0,
    rating: 4.3,
    likeCount: 2500,
    pageCount: 448,
    tags: ['Forensik', 'Dorf', 'Serienmörder'],
    description: {
      de: 'Forensiker David Hunter wollte nie wieder mit Toten arbeiten – dann findet das Dorf eine Leiche.',
      en: 'Forensic expert David Hunter swore off the dead — then the village finds a body.',
    },
    query: { title: 'The Chemistry of Death', author: 'Simon Beckett' },
  },
  {
    title: 'Erbarmen',
    author: 'Jussi Adler-Olsen',
    genre: 'Thriller',
    price: 11.0,
    rating: 4.2,
    likeCount: 2300,
    pageCount: 432,
    tags: ['Skandinavien', 'Cold Case', 'Sonderdezernat Q'],
    description: {
      de: 'Carl Mørck übernimmt das Sonderdezernat Q – und einen Fall, der seit fünf Jahren als gelöst gilt.',
      en: 'Carl Mørck takes over Department Q — and a case everyone closed five years ago.',
    },
    query: { title: 'The Keeper of Lost Causes', author: 'Jussi Adler-Olsen' },
  },

  // ── Sachbuch (Erweiterung) ─────────────────────────────────
  {
    title: 'Homo Deus',
    author: 'Yuval Noah Harari',
    genre: 'Sachbuch',
    price: 16.0,
    rating: 4.4,
    likeCount: 3900,
    pageCount: 576,
    tags: ['Zukunft', 'Menschheit', 'Technologie'],
    description: {
      de: 'Was kommt nach dem Homo sapiens? Eine Geschichte von Morgen zwischen Algorithmen und Unsterblichkeit.',
      en: 'What comes after Homo sapiens? A history of tomorrow between algorithms and immortality.',
    },
    query: { title: 'Homo Deus', author: 'Harari' },
  },
  {
    title: 'Die 1%-Methode',
    author: 'James Clear',
    genre: 'Sachbuch',
    price: 15.0,
    rating: 4.6,
    likeCount: 5600,
    pageCount: 368,
    tags: ['Gewohnheiten', 'Selbstoptimierung', 'Bestseller'],
    description: {
      de: 'Minimale Veränderungen, verblüffende Ergebnisse: wie kleine Gewohnheiten Großes bewirken.',
      en: 'Tiny changes, remarkable results: how small habits compound into big outcomes.',
    },
    query: { title: 'Atomic Habits', author: 'James Clear' },
  },
  {
    title: 'Die subtile Kunst des Daraufscheißens',
    author: 'Mark Manson',
    genre: 'Sachbuch',
    price: 13.0,
    rating: 4.1,
    likeCount: 4100,
    pageCount: 224,
    tags: ['Lebenshilfe', 'Provokant', 'Prioritäten'],
    description: {
      de: 'Nicht alles verdient deine Energie – ein unbequemer Ratgeber über die richtigen Prioritäten.',
      en: 'Not everything deserves your energy — an uncomfortable guide to choosing what matters.',
    },
    query: { title: 'The Subtle Art of Not Giving a F*ck', author: 'Mark Manson' },
  },
  {
    title: 'Becoming – Meine Geschichte',
    author: 'Michelle Obama',
    genre: 'Sachbuch',
    price: 17.0,
    rating: 4.7,
    likeCount: 5200,
    pageCount: 544,
    tags: ['Memoiren', 'Politik', 'Inspiration'],
    description: {
      de: 'Von der South Side Chicagos ins Weiße Haus – Michelle Obamas Weg in ihren eigenen Worten.',
      en: 'From Chicago’s South Side to the White House — Michelle Obama’s journey in her own words.',
    },
    query: { title: 'Becoming', author: 'Michelle Obama' },
  },
  {
    title: 'Das Café am Rande der Welt',
    author: 'John Strelecky',
    genre: 'Sachbuch',
    price: 9.0,
    rating: 4.2,
    likeCount: 3400,
    pageCount: 128,
    tags: ['Lebenssinn', 'Parabel', 'Kurz'],
    description: {
      de: 'Drei Fragen auf einer Speisekarte stellen Johns ganzes Leben auf den Kopf.',
      en: 'Three questions on a café menu turn John’s entire life upside down.',
    },
    query: { title: 'The Why Cafe', author: 'John Strelecky' },
  },
  {
    title: 'Darm mit Charme',
    author: 'Giulia Enders',
    genre: 'Sachbuch',
    price: 12.0,
    rating: 4.4,
    likeCount: 3700,
    pageCount: 304,
    tags: ['Medizin', 'Humor', 'Körper'],
    description: {
      de: 'Unser unterschätztes Organ: charmant erklärt, warum der Darm fast alles mitentscheidet.',
      en: 'Our most underrated organ: a charming tour of why the gut has a say in almost everything.',
    },
    query: { title: 'Gut: The Inside Story', author: 'Giulia Enders' },
  },
  {
    title: 'Warum wir schlafen',
    author: 'Matthew Walker',
    genre: 'Sachbuch',
    price: 14.0,
    rating: 4.5,
    likeCount: 3100,
    pageCount: 480,
    tags: ['Schlaf', 'Gesundheit', 'Wissenschaft'],
    description: {
      de: 'Schlaf ist die beste Gesundheitsvorsorge, die es gibt – und wir wissen erstaunlich wenig darüber.',
      en: 'Sleep is the best health insurance there is — and we know astonishingly little about it.',
    },
    query: { title: 'Why We Sleep', author: 'Matthew Walker' },
  },
  {
    title: 'Der Mann, der seine Frau mit einem Hut verwechselte',
    author: 'Oliver Sacks',
    genre: 'Sachbuch',
    price: 12.0,
    rating: 4.3,
    likeCount: 2200,
    pageCount: 320,
    tags: ['Neurologie', 'Fallgeschichten', 'Klassiker'],
    description: {
      de: 'Neurologische Fallgeschichten, die zeigen, wie zerbrechlich und wunderbar unser Gehirn ist.',
      en: 'Neurological case stories revealing how fragile and wondrous the brain really is.',
    },
    query: { title: 'The Man Who Mistook His Wife for a Hat', author: 'Oliver Sacks' },
  },
  {
    title: 'Unser Kosmos',
    author: 'Carl Sagan',
    genre: 'Sachbuch',
    price: 16.0,
    rating: 4.6,
    likeCount: 2800,
    pageCount: 432,
    tags: ['Astronomie', 'Klassiker', 'Staunen'],
    description: {
      de: 'Eine Reise durch Raum und Zeit – und eine Liebeserklärung an die wissenschaftliche Neugier.',
      en: 'A voyage through space and time — and a love letter to scientific curiosity.',
    },
    query: { title: 'Cosmos', author: 'Carl Sagan' },
  },
  {
    title: 'Befreit',
    author: 'Tara Westover',
    genre: 'Sachbuch',
    price: 14.0,
    rating: 4.6,
    likeCount: 3500,
    pageCount: 448,
    tags: ['Memoiren', 'Bildung', 'Familie'],
    description: {
      de: 'Aufgewachsen ohne Schule in den Bergen Idahos – und der lange Weg bis nach Cambridge.',
      en: 'Raised without schooling in the Idaho mountains — and the long road to Cambridge.',
    },
    query: { title: 'Educated', author: 'Tara Westover' },
  },
];
